# Generated by Django 4.0.2 on 2022-03-03 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категорія')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Пост')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image_post', models.ImageField(upload_to='image_post/', verbose_name='Зображення поста')),
                ('image_cod', models.ImageField(upload_to='image_cod/', verbose_name='Зображення коду')),
                ('image_res', models.ImageField(upload_to='image_res/', verbose_name='Зображення результату')),
                ('description', models.TextField(verbose_name='Описання')),
                ('description_cod', models.TextField(verbose_name='Описання коду')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата і час створення')),
                ('time_update', models.DateTimeField(auto_now_add=True, verbose_name='Дата і час публікації')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='blog.category')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Пости',
            },
        ),
    ]
