# Generated by Django 4.0.2 on 2022-02-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='image_category/', verbose_name='Зображення Категорії'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_post',
            field=models.ImageField(upload_to='image_post/', verbose_name='Зображення поста'),
        ),
    ]
